#!/bin/bash -ex

# update rails/rack to correct versions
cd /var/www/railsapp
gem install rails -v=2.3.14
gem install rack -v=1.1.0

# do the stuff in the redmine upgrade doc
rake config/initializers/session_store.rb

# run db migrations
rake db:migrate RAILS_ENV=production 
rake db:migrate_plugins RAILS_ENV=production 

# the docs are crap for this bit (what is a 'newer version'?) so let's do this too
rake generate_session_store

# clean up
rake tmp:cache:clear
rake tmp:sessions:clear

# restart apache to finish
service apache2 restart
